server:
  port: 8080
spring:
  messages:
    basename: ValidationMessages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  application:
    name: unified-biztool
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
app:
  token:
    encrypt:
      password: ${AES_PASSWORD}
      salt: ${AES_SALT}
