server:
  port: 8080
  servlet:
    session:
      timeout: 60m
spring:
  messages:
    basename: ValidationMessages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  application:
    name: unified-biztool
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
app:
  token:
    encrypt:
      password: ${AES_PASSWORD}
      salt: ${AES_SALT}
