server:
  port: 8080
spring:
  messages:
    basename: ValidationMessages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  application:
    name: unified-biztool
  datasource:
    url: jdbc:mysql://${DB_HOST}/unified-biztool?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
app:
  token:
    encrypt:
      password: ${AES_PASSWORD}
      salt: ${AES_SALT}
